version: '3.8'

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - 8096:8096
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /mnt/hdd/jellyfin/config:/config
      - /mnt/hdd/jellyfin/cache:/cache
      - /mnt/hdd/Filme/Movies:/media/movies
      - /mnt/hdd/Filme/Shows:/media/shows
      - /mnt/hdd/Filme/Kids:/media/kids
    devices:
      - /dev/dri:/dev/dri

  caddy:
    image: caddy
    container_name: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  samba:
    image: ghcr.io/servercontainers/samba
    container_name: samba
    restart: unless-stopped
    # Expose ports directly instead of using host network mode for better security
    ports:
      - "139:139"
      - "445:445"
    environment:
      AVAHI_NAME: StorageServer
      MODEL: 'MacSamba'
      SAMBA_CONF_LOG_LEVEL: 3

      # User configuration
      ACCOUNT_jkrumm: ${SAMBA_PASSWORD}
      UID_jkrumm: 1000
      GROUP_jkrumm: 1000

      # Global configuration for macOS compatibility
      SAMBA_GLOBAL_CONFIG: |
        [global]
        min protocol = SMB2
        ea support = yes
        vfs objects = fruit streams_xattr
        fruit:metadata = stream
        fruit:model = MacSamba
        fruit:veto_appledouble = no
        fruit:nfs_aces = no
        fruit:wipe_intentionally_left_blank_rfork = yes
        fruit:delete_empty_adfiles = yes
        fruit:posix_rename = yes

      # Share configurations
      SAMBA_VOLUME_CONFIG_ssd: "[SSD]
        path = /mnt/ssd
        valid users = jkrumm
        guest ok = no
        read only = no
        browseable = yes"

      SAMBA_VOLUME_CONFIG_hdd: "[HDD]
        path = /mnt/hdd
        valid users = jkrumm
        guest ok = no
        read only = no
        browseable = yes"

    volumes:
      - /home/jkrumm/ssd:/mnt/ssd  # Path to SSD
      - /mnt/hdd:/mnt/hdd          # Path to HDD

volumes:
  caddy_data:
  caddy_config: