version: '2' # We need v2 because of https://github.com/docker/compose/issues/3328 (group_add)
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - 8096:8096
    security_opt:
      - no-new-privileges:true
    user: "1000:1000"  # Replace with your actual user and group ID
    group_add:
      - "993"  # Use the render group ID
    environment:
      - TZ=Europe/Berlin
      - UMASK_SET=022
      - DISPLAY=:0
      - LIBVA_DRIVER_NAME=iHD
    volumes:
      - ~/jellyfin/config:/config
      - ~/jellyfin/cache:/cache
      - /mnt/hdd/Filme/Movies:/media/movies
      - /mnt/hdd/Filme/Shows:/media/shows
      - /mnt/hdd/Filme/Kids:/media/kids
      - /dev/shm:/transcode
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card1:/dev/dri/card1

  caddy:
    image: caddy
    container_name: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: