version: "3.8"

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - 8096:8096
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /mnt/hdd/jellyfin/config:/config
      - /mnt/hdd/jellyfin/cache:/cache
      - /mnt/hdd/Filme/Movies:/media/movies
      - /mnt/hdd/Filme/Shows:/media/shows
      - /mnt/hdd/Filme/Kids:/media/kids
    devices:
      - /dev/dri:/dev/dri
    labels:
      glance.name: Jellyfin
      glance.icon: si:jellyfin
      glance.url: https://jellyfin.jkrumm.dev
      glance.hide: false

  caddy:
    image: caddy
    container_name: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    labels:
      glance.parent: uptime
      glance.name: Caddy
      glance.hide: false

  samba:
    image: ghcr.io/servercontainers/samba
    container_name: samba
    restart: unless-stopped
    ports:
      - "139:139"
      - "445:445"
    environment:
      AVAHI_NAME: StorageServer
      MODEL: "Macmini"
      SAMBA_CONF_LOG_LEVEL: 3
      ACCOUNT_jkrumm: ${SAMBA_PASSWORD}
      SAMBA_GLOBAL_CONFIG: "[global]; min protocol=SMB2; ea support=yes; vfs objects=fruit streams_xattr; fruit:metadata=stream; fruit:model=MacSamba; fruit:veto_appledouble=no; fruit:nfs_aces=no; fruit:wipe_intentionally_left_blank_rfork=yes; fruit:delete_empty_adfiles=yes; fruit:posix_rename=yes"
      SAMBA_VOLUME_CONFIG_ssd: "[SSD]; path=/mnt/ssd; valid users=jkrumm; guest ok=no; read only=no; browseable=yes; comment=SSD"
      SAMBA_VOLUME_CONFIG_hdd: "[HDD]; path=/mnt/hdd; valid users=jkrumm; guest ok=no; read only=no; browseable=yes; comment=HDD"
    volumes:
      - /home/jkrumm/ssd:/mnt/ssd
      - /mnt/hdd:/mnt/hdd
    labels:
      glance.name: Samba
      glance.icon: si:protondrive
      glance.url: https://samba.jkrumm.dev
      glance.hide: false

  beszel:
    image: henrygd/beszel
    container_name: beszel
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - /mnt/hdd/beszel:/beszel_data
    labels:
      glance.name: Beszel
      glance.icon: si:graylog
      glance.url: https://beszel.jkrumm.dev
      glance.hide: false

  beszel-agent:
    image: "henrygd/beszel-agent"
    container_name: beszel-agent
    restart: unless-stopped
    ports:
      - 45876:45876
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/hdd/.beszel:/extra-filesystems/hdd:ro
    environment:
      PORT: 45876
      KEY: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIInimIOc9SESgXhpaYcyJWwf/JZmP7WSvHtdqhPqMZEf"
      FILESYSTEMS: /sda/sda3
    labels:
      glance.hide: true

  glance:
    image: glanceapp/glance
    container_name: glance
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8080:8080
    restart: unless-stopped
    labels:
      glance.name: Glance
      glance.parent: uptime
      glance.icon: si:hashnode
      glance.url: https://home.jkrumm.dev
      glance.hide: false

  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - SETTINGS_ENCRYPTION_KEY=${DUPLICATI_ENCRYPTION_KEY}
      - DUPLICATI__WEBSERVICE_PASSWORD=${DUPLICATI_WEBSERVICE_PASSWORD}
    # - CLI_ARGS= #optional
    volumes:
      - /mnt/hdd/duplicati/config:/config
      - /mnt/transfer/duplicati_backups:/backups
      - /home/jkrumm/ssd:/source/ssd
      - /mnt:/source/mnt
    ports:
      - 8200:8200
    restart: unless-stopped
    labels:
      glance.name: Duplicati
      glance.icon: si:duplicati
      glance.url: https://duplicati.jkrumm.dev
      glance.hide: false

  porkbun-ddns:
    image: "mietzen/porkbun-ddns:latest"
    container_name: porkbun-ddns
    environment:
      DOMAIN: "jkrumm.dev"
      SUBDOMAINS: "beszel,duplicati,home,jellyfin,samba,uptime,homelab,dozzle"
      SECRETAPIKEY: ${PORKBUN_API_SECRET}
      APIKEY: ${PORKBUN_API_KEY}
      FRITZBOX_IP: "169.254.1.1"
      IPV6: "TRUE"
      IPV4: "FALSE"
    restart: unless-stopped
    networks:
      - porkbun_ddns_network
    labels:
      glance.parent: uptime
      glance.name: Porkbun DDNS
      glance.icon: si:porkbun
      glance.hide: false

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    command:
      - --cleanup=true
    restart: unless-stopped
    environment:
      WATCHTOWER_NOTIFICATION_URL: ${WATCHTOWER_NOTIFICATION_URL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      glance.parent: uptime
      glance.name: Watchtower
      glance.icon: si:watchtower
      glance.hide: false

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - "3010:3001"
    volumes:
      - /mnt/hdd/uptimekuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      glance.name: Uptime Kuma
      glance.icon: si:uptimekuma
      glance.url: https://uptime.jkrumm.dev
      glance.hide: false
      glance.id: uptime

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    environment:
      DOZZLE_HOSTNAME: jkrumm.dev
      DOZZLE_ADDR: :8081
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8081:8081
    labels:
      glance.name: Dozzle
      glance.parent: uptime
      glance.icon: si:logstash
      glance.url: https://dozzle.jkrumm.dev
      glance.hide: false

volumes:
  caddy_data:
  caddy_config:

networks:
  porkbun_ddns_network:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
